tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "background": "#f6fafe",
                "secondary": "#48626e",
                "tertiary": "#602400",
                "surface-dim": "#d6dade",
                "on-primary-container": "#a5bdff",
                "surface-container": "#eaeef2",
                "surface-tint": "#2559bd",
                "surface": "#f6fafe",
                "on-primary-fixed-variant": "#00419e",
                "inverse-primary": "#b1c5ff",
                "tertiary-container": "#843500",
                "on-secondary-container": "#4e6874",
                "surface-container-highest": "#dfe3e7",
                "inverse-on-surface": "#edf1f5",
                "on-tertiary-fixed": "#341100",
                "on-background": "#171c1f",
                "on-primary-fixed": "#001946",
                "surface-variant": "#dfe3e7",
                "surface-container-low": "#f0f4f8",
                "inverse-surface": "#2c3134",
                "tertiary-fixed-dim": "#ffb692",
                "surface-bright": "#f6fafe",
                "secondary-container": "#cbe7f5",
                "tertiary-fixed": "#ffdbcb",
                "primary-fixed-dim": "#b1c5ff",
                "outline": "#737784",
                "on-surface-variant": "#434653",
                "primary-fixed": "#dae2ff",
                "on-secondary-fixed-variant": "#304a55",
                "secondary-fixed-dim": "#afcbd8",
                "primary-container": "#0047ab",
                "primary": "#00327d",
                "outline-variant": "#c3c6d5",
                "on-primary": "#ffffff",
                "secondary-fixed": "#cbe7f5",
                "surface-container-high": "#e4e9ed",
                "on-tertiary-container": "#ffaa80",
                "error-container": "#ffdad6",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#171c1f",
                "on-tertiary": "#ffffff",
                "on-error": "#ffffff",
                "error": "#ba1a1a",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed-variant": "#7a3000",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#021f29"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
}
