tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#304a55",
        "primary-fixed-dim": "#b1c5ff",
        "surface-dim": "#d6dade",
        "surface": "#f6fafe",
        "outline": "#737784",
        "on-tertiary-container": "#ffaa80",
        "background": "#f6fafe",
        "surface-tint": "#2559bd",
        "on-tertiary-fixed": "#341100",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#021f29",
        "surface-container-high": "#e4e9ed",
        "on-primary-fixed": "#001946",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c6d5",
        "secondary-container": "#cbe7f5",
        "surface-bright": "#f6fafe",
        "secondary-fixed": "#cbe7f5",
        "primary": "#00327d",
        "secondary-fixed-dim": "#afcbd8",
        "on-primary": "#ffffff",
        "surface-variant": "#dfe3e7",
        "on-error-container": "#93000a",
        "on-secondary-container": "#4e6874",
        "primary-container": "#0047ab",
        "inverse-on-surface": "#edf1f5",
        "inverse-surface": "#2c3134",
        "on-primary-container": "#a5bdff",
        "inverse-primary": "#b1c5ff",
        "on-background": "#171c1f",
        "surface-container-highest": "#dfe3e7",
        "surface-container-low": "#f0f4f8",
        "tertiary-fixed": "#ffdbcb",
        "tertiary-fixed-dim": "#ffb692",
        "tertiary": "#602400",
        "on-tertiary-fixed-variant": "#7a3000",
        "surface-container": "#eaeef2",
        "tertiary-container": "#843500",
        "primary-fixed": "#dae2ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#171c1f",
        "on-primary-fixed-variant": "#00419e",
        "on-surface-variant": "#434653",
        "secondary": "#48626e"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "1rem", "xl": "1.5rem", "full": "9999px" },
    },
  },
}
